"""Generate docs/operations.md and docs/errors.md from the code registries.

    uv run python scripts/gen_docs.py          # rewrite the files
    uv run python scripts/gen_docs.py --check  # exit 1 if they are out of date (the tests do this)
"""
import sys
from pathlib import Path

from ancestry_cli import runtime
from ancestry_cli.ops import SPECS

DOCS = Path(__file__).resolve().parents[1] / "docs"

_RISK = {
    "additive": "adds content only",
    "edit": "changes existing content (restorable from the before-snapshot)",
    "structural": "adds a person or a relationship",
    "destructive": "removes content",
    "hint-state": "moves a hint between New / Undecided / Ignored / Rejected",
}


def operations_md():
    out = ["# Write operations", "",
           "<!-- generated by scripts/gen_docs.py from src/ancestry_cli/ops.py; do not edit by hand -->", "",
           "Run `ancestry write <op> --tree T --person P [--assertion A] --set key=value ... [--live]`. Without `--live` it is a",
           "dry-run that shows the request shape. `ancestry ops [name]` prints this information as JSON.", "",
           "Risk classes:", ""]
    out += [f"- **{k}**: {v}" for k, v in _RISK.items()]
    out += ["", "| operation | risk | required | summary |", "|---|---|---|---|"]
    out += [f"| [`{n}`](#{n}) | {s.risk} | {', '.join(f'`{r}`' for r in s.required) or '-'} | {s.summary} |" for n, s in SPECS.items()]
    for name, spec in SPECS.items():
        out += ["", f"## {name}", "", spec.summary, "",
                f"- **Risk:** {spec.risk}",
                f"- **Required:** {', '.join(f'`{r}`' for r in spec.required) or 'nothing beyond --tree and --person'}",
                f"- **Optional:** {', '.join(f'`{o}`' for o in spec.optional) or '-'}",
                f"- **Undo:** {spec.undo}"]
        if spec.notes:
            out.append(f"- **Notes:** {spec.notes}")
        out += ["", "```bash", f"ancestry write {name} --tree TREE --person PERSON {spec.example} --confirm-tree TREE --live", "```"]
    return "\n".join(out) + "\n"


def _action(a):
    if a["kind"] == "run":
        text = "`" + " ".join(a["argv"]) + "`"
    elif a["kind"] == "retry":
        text = "retry the same command"
    else:
        text = a["say"]
    return f"{a['kind']}: {text}" + (f" *({a['when']})*" if a.get("when") else "")


def errors_md():
    out = ["# Error classifications", "",
           "<!-- generated by scripts/gen_docs.py from src/ancestry_cli/runtime.py; do not edit by hand -->", "",
           "A failing result is `{\"ok\": false, \"classification\": ..., \"state\": ..., \"dispatch_attempted\": ...}` plus, for the codes below,",
           "`retryable`, `needs_human`, `hint` and `next_actions`. See [agents.md](agents.md) for how to act on them.", "",
           "**Fields**", "",
           "- `state`: what you may assume about the tree. `unchanged` (nothing was sent, or the server clearly refused), `unknown` (a request",
           "  left and the result is not known: verify before doing anything else), `changed` (confirmed).",
           "- `retryable`: safe to re-run the identical command (after `retry_after` seconds when given). Never true when `state` is `unknown`.",
           "- `needs_human`: something only the owner can do (sign in, solve a challenge, edit config).",
           "- `next_actions`: ordered recovery steps. `run` gives the exact argv (ids filled in; `<name>` marks a choice you make), `retry`",
           "  re-runs the same command, `human` says what the owner must do, `edit-args` says what to change in your arguments.",
           "- `problems` (validation errors): `[{field, issue: missing|invalid|not-allowed|unknown-value, expected?, valid_values?, did_you_mean?}]`.",
           "- `journal_id`: the journal entry for a request that was sent. `progress`: `{done, failed_at}` for multi-request operations.",
           "- `warnings`: `[{code, message}]` for non-fatal issues; may appear on successful results.",
           "- `details`: safe context (`status`, `server_error_code`, `response_shape`). Never values from your tree.", "",
           "Exit codes: `0` ok, `1` failed with nothing changed, `2` bad usage, `3` state unknown (stop and verify).", "",
           "| classification | retryable | needs a human | what to do | next actions |", "|---|---|---|---|---|"]
    for code, err in runtime.ERRORS.items():
        actions = "<br>".join(_action(a) for a in err.actions)
        out.append(f"| `{code}` | {'yes' if err.retryable else 'no'} | {'yes' if err.needs_human else 'no'} | {err.hint.replace('{port}', '9224')} | {actions} |")
    return "\n".join(out) + "\n"


FILES = {"operations.md": operations_md, "errors.md": errors_md}


def main(check=False):
    stale = []
    for name, render in FILES.items():
        path = DOCS / name
        text = render()
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(name)
        else:
            path.write_text(text)
    if check and stale:
        print("out of date: " + ", ".join(stale) + " (run scripts/gen_docs.py)")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main("--check" in sys.argv))
